version: "3.8"

networks:
  traefik-network:
    driver: overlay
    external: true

  db-network:
    driver: overlay
    external: true

services:
  feedmama-sidekiq:
    image: tanngoc93/feedmama:latest
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    working_dir: /app
    environment:
      RAILS_MASTER_KEY: ""
      #
      DATABASE_POOL:     5
      DATABASE_HOST:     ""
      DATABASE_PORT:     ""
      DATABASE_USER:     ""
      DATABASE_PASSWORD: ""
      REDIS_URL:         ""
      RAILS_ENV:         ""
      PORT: 3000
      #
      KOALA_APP_ID:      ""
      KOALA_APP_SECRET:  ""
    command: /bin/sh "/app/.dockerdev/commander/sidekiq.sh"
    depends_on:
      - db
      - redis
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=false"
        - "traefik.docker.network=db-network"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    networks:
      - db-network
      - traefik-network
