version: "3.8"

networks:
  traefik-network:
    driver: overlay
    external: true

  db-network:
    driver: overlay
    external: true

services:
  feedmama-backend:
    image: tanngoc93/feedmama:latest
    working_dir: /app
    environment:
      RAILS_MASTER_KEY: ""
      #
      DATABASE_POOL:     5
      DATABASE_HOST:     ""
      DATABASE_PORT:     ""
      DATABASE_USER:     ""
      DATABASE_PASSWORD: ""
      REDIS_URL:         ""
      RAILS_ENV:         ""
      PORT: 3000
      #
      KOALA_APP_ID:      ""
      KOALA_APP_SECRET:  ""
    command: /bin/sh "/app/.dockerdev/commander/rails.sh"
    depends_on:
      - db
      - redis
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-network"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        # 
        - "traefik.http.routers.feedmama-http.rule=Host(`domain.com`)"
        - "traefik.http.routers.feedmama-http.entrypoints=web"
        - "traefik.http.routers.feedmama-http.middlewares=redirect-to-https@docker"
        #
        - "traefik.http.services.feedmama-service.loadbalancer.server.port=3000"
        # 
        - "traefik.http.routers.feedmama-secured.rule=Host(`domain.com`)"
        - "traefik.http.routers.feedmama-secured.entrypoints=websecured"
        - "traefik.http.routers.feedmama-secured.tls.certresolver=myhttpchallenge"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    networks:
      - db-network
      - traefik-network
