version: "3.8"

networks:
  traefik-network:
    driver: overlay
    external: true

  db-network:
    driver: overlay
    external: true

services:
  wordpress:
    image: tanngoc93/wordpress:latest
    working_dir: /var/www/html
    environment:
      WORDPRESS_DB_HOST:      ""
      WORDPRESS_DB_USER:      ""
      WORDPRESS_DB_PASSWORD:  ""
      WORDPRESS_DB_NAME:      ""
      WORDPRESS_TABLE_PREFIX: ""
    volumes:
      - /www/ghiencham/wp-content:/usr/src/wordpress/wp-content
      - /www/ghiencham/wp-config/wp-config.php:/usr/src/wordpress/wp-config.php
      - /www/ghiencham/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-network"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        #
        - "traefik.http.routers.ghiencham-http.rule=Host(`domain.com`, `www.domain.com`)"
        - "traefik.http.routers.ghiencham-http.entrypoints=web"
        - "traefik.http.routers.ghiencham-http.middlewares=redirect-to-https@docker"
        #
        - "traefik.http.services.ghiencham-service.loadbalancer.server.port=80"
        #
        - "traefik.http.routers.ghiencham-secured.rule=Host(`domain.com`)"
        - "traefik.http.routers.ghiencham-secured.entrypoints=websecured"
        - "traefik.http.routers.ghiencham-secured.tls.certresolver=myhttpchallenge"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any
    networks:
      - db-network
      - traefik-network
