version: "3.8"

networks:
  traefik-network:
    driver: overlay
    external: true

services:
  traefik:
    image: traefik:v2.6.6
    volumes:
      - "/root/www/traefik/letsencrypt:/letsencrypt"
      - "/root/www/traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik-network
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik-network"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
        #
        - "traefik.http.routers.proxy.rule=Host(`traefik.${DOMAIN}`)"
        - "traefik.http.routers.proxy.entrypoints=web"
        - "traefik.http.routers.proxy.middlewares=redirect-to-https@docker"
        # 
        - "traefik.http.services.proxy-svc.loadbalancer.server.port=8080"
        # 
        - "traefik.http.routers.proxy-secured.rule=Host(`traefik.${DOMAIN}`)"
        - "traefik.http.routers.proxy-secured.entrypoints=websecured"
        - "traefik.http.routers.proxy-secured.service=api@internal"
        - "traefik.http.routers.proxy-secured.tls=true"
        - "traefik.http.routers.proxy-secured.tls.certresolver=myhttpchallenge"
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: any

  system-prune:
    image: docker
    command: docker system prune --all --force
    deploy:
      mode: global
      labels:
        - "traefik.enable=false"
      restart_policy:
        delay: 24h
