defaults: &defaults
  working_directory: ~/buildbox
  docker:
    - image: cimg/ruby:3.1.2

# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.18

      - run:
          name: Login to Docker registry
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build image
          command: docker build --build-arg ARG_RAILS_MASTER_KEY=$ARG_RAILS_MASTER_KEY -t tanngoc93/feedmama:latest -f .dockerdev/Dockerfile .
          
      - run:
          name: Push to Docker registry 
          command: docker push tanngoc93/feedmama:latest

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-production-image:
    jobs:
      - build:
          filters:
            branches:
              only: main
