defaults: &defaults
  working_directory: ~/buildbox
  docker:
    - image: cimg/ruby:3.1.2

# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

jobs:
  build-docker-image:
    <<: *defaults
    steps:
      - checkout

      - setup_remote_docker:
          version: 20.10.18

      - run:
          name: Login to docker registry
          command: docker login -u $DOCKER_USER -p $DOCKER_PASS

      - run:
          name: Build docker image
          command: docker build --build-arg ARG_RAILS_MASTER_KEY=$ARG_RAILS_MASTER_KEY -t tanngoc93/feedmama:latest -f .dockerdev/Dockerfile .
          
      - run:
          name: Push docker image to registry 
          command: docker push tanngoc93/feedmama:latest

  deploy-server:
    machine:
      enabled: true

    steps:
      - add_ssh_keys:
          fingerprints:
            - "a9:d7:06:ac:4f:96:df:55:d9:d4:d7:ab:c8:96:46:26"
            
      - run:
          name: SSH Keyscan
          command: |
            ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts

      - run:
          name: Deploy server 
          command: |
            ssh $SSH_USER@$SSH_HOST "docker compose -f $DOCKER_COMPOSE_PATH stop && docker rmi $DOCKER_IMAGE:$DOCKER_TAG -f && docker pull $DOCKER_IMAGE:$DOCKER_TAG && docker compose -f $DOCKER_COMPOSE_PATH start"

      - run:
          name: Clean server 
          command: |
            ssh $SSH_USER@$SSH_HOST "docker system prune -f"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-deploy:
    jobs:
      - build-docker-image
      - deploy-server:
          requires:
            - build-docker-image # only deploy once build job has completed
          filters:
            branches:
              only: main

