default: &default
  adapter:  mysql2
  encoding: utf8mb4
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host:     <%= ENV.fetch("DATABASE_HOST")     { 'localhost' } %>
  username: <%= ENV.fetch("DATABASE_USER")     { 'root' } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { 'password' } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_DEVELOPMENT") { 'db_dev' } %>

test:
  <<: *default
  database: <%= ENV.fetch("DATABASE_TEST")        { 'db_test' } %>

production:
  <<: *default
  database: <%= ENV.fetch("DATABASE_PRODUCTION")  { 'db_production' } %>