---
:logfile: ./log/sidekiq.log
:queues:
  - default
  - mailers
  - abandoned_order_check

development:
  :concurrency: 10

test:
  :concurrency: 10

staging:
  :concurrency: 10

production:
  :concurrency: 50